version: "3"
services:
  weeb:
    restart: always
    build: .
    ports:
      - 86:3900
    volumes:
      - ./:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
